# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/yusuk/DAIKICHI/MIIL/MIIL_LEARNING_GUI.ui',
# licensing of 'C:/Users/yusuk/DAIKICHI/MIIL/MIIL_LEARNING_GUI.ui' applies.
#
# Created: Fri Jan 31 10:09:12 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 733)
        MainWindow.setMinimumSize(QtCore.QSize(951, 733))
        MainWindow.setMaximumSize(QtCore.QSize(951, 733))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setEnabled(False)
        self.label1.setGeometry(QtCore.QRect(820, 580, 281, 141))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 380, 931, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_5.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton1.setGeometry(QtCore.QRect(10, 20, 91, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton1.setFont(font)
        self.pushButton1.setDefault(True)
        self.pushButton1.setObjectName("pushButton1")
        self.groupBox_55 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_55.setGeometry(QtCore.QRect(10, 90, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_55.setFont(font)
        self.groupBox_55.setObjectName("groupBox_55")
        self.lineEdit7 = QtWidgets.QLineEdit(self.groupBox_55)
        self.lineEdit7.setEnabled(False)
        self.lineEdit7.setGeometry(QtCore.QRect(10, 20, 591, 20))
        self.lineEdit7.setObjectName("lineEdit7")
        self.pushButton9 = QtWidgets.QPushButton(self.groupBox_55)
        self.pushButton9.setGeometry(QtCore.QRect(710, 20, 93, 28))
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton17 = QtWidgets.QPushButton(self.groupBox_55)
        self.pushButton17.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.pushButton17.setObjectName("pushButton17")
        self.pushButton24 = QtWidgets.QPushButton(self.groupBox_55)
        self.pushButton24.setGeometry(QtCore.QRect(610, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton24.setFont(font)
        self.pushButton24.setAutoDefault(False)
        self.pushButton24.setDefault(False)
        self.pushButton24.setFlat(False)
        self.pushButton24.setObjectName("pushButton24")
        self.groupBox_53 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_53.setGeometry(QtCore.QRect(10, 230, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_53.setFont(font)
        self.groupBox_53.setObjectName("groupBox_53")
        self.lineEdit3 = QtWidgets.QLineEdit(self.groupBox_53)
        self.lineEdit3.setEnabled(False)
        self.lineEdit3.setGeometry(QtCore.QRect(10, 20, 691, 20))
        self.lineEdit3.setObjectName("lineEdit3")
        self.pushButton4 = QtWidgets.QPushButton(self.groupBox_53)
        self.pushButton4.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton25 = QtWidgets.QPushButton(self.groupBox_53)
        self.pushButton25.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton25.setFont(font)
        self.pushButton25.setAutoDefault(False)
        self.pushButton25.setDefault(False)
        self.pushButton25.setFlat(False)
        self.pushButton25.setObjectName("pushButton25")
        self.groupBox_51 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_51.setGeometry(QtCore.QRect(550, 20, 251, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_51.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_51.setFont(font)
        self.groupBox_51.setObjectName("groupBox_51")
        self.radioButton1 = QtWidgets.QRadioButton(self.groupBox_51)
        self.radioButton1.setGeometry(QtCore.QRect(90, 20, 91, 16))
        self.radioButton1.setChecked(False)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(self.groupBox_51)
        self.radioButton2.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.radioButton2.setChecked(True)
        self.radioButton2.setObjectName("radioButton2")
        self.radioButton3 = QtWidgets.QRadioButton(self.groupBox_51)
        self.radioButton3.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton3.setChecked(False)
        self.radioButton3.setObjectName("radioButton3")
        self.radioButton4 = QtWidgets.QRadioButton(self.groupBox_51)
        self.radioButton4.setGeometry(QtCore.QRect(90, 40, 81, 16))
        self.radioButton4.setChecked(False)
        self.radioButton4.setObjectName("radioButton4")
        self.radioButton5 = QtWidgets.QRadioButton(self.groupBox_51)
        self.radioButton5.setGeometry(QtCore.QRect(190, 20, 51, 16))
        self.radioButton5.setChecked(False)
        self.radioButton5.setObjectName("radioButton5")
        self.groupBox_54 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_54.setGeometry(QtCore.QRect(110, 20, 81, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_54.setFont(font)
        self.groupBox_54.setObjectName("groupBox_54")
        self.comboBox1 = QtWidgets.QComboBox(self.groupBox_54)
        self.comboBox1.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.comboBox1.setObjectName("comboBox1")
        self.groupBox_52 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_52.setGeometry(QtCore.QRect(200, 20, 81, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_52.setFont(font)
        self.groupBox_52.setObjectName("groupBox_52")
        self.lineEdit10 = QtWidgets.QLineEdit(self.groupBox_52)
        self.lineEdit10.setEnabled(True)
        self.lineEdit10.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.lineEdit10.setObjectName("lineEdit10")
        self.groupBox_48 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_48.setGeometry(QtCore.QRect(390, 20, 71, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_48.setFont(font)
        self.groupBox_48.setObjectName("groupBox_48")
        self.comboBox7 = QtWidgets.QComboBox(self.groupBox_48)
        self.comboBox7.setGeometry(QtCore.QRect(10, 20, 51, 22))
        self.comboBox7.setObjectName("comboBox7")
        self.groupBox_49 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_49.setGeometry(QtCore.QRect(470, 20, 71, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_49.setFont(font)
        self.groupBox_49.setObjectName("groupBox_49")
        self.comboBox8 = QtWidgets.QComboBox(self.groupBox_49)
        self.comboBox8.setGeometry(QtCore.QRect(10, 20, 51, 22))
        self.comboBox8.setObjectName("comboBox8")
        self.groupBox_50 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_50.setGeometry(QtCore.QRect(290, 20, 91, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_50.setFont(font)
        self.groupBox_50.setObjectName("groupBox_50")
        self.lineEdit11 = QtWidgets.QLineEdit(self.groupBox_50)
        self.lineEdit11.setEnabled(True)
        self.lineEdit11.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.lineEdit11.setObjectName("lineEdit11")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 160, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.lineEdit9 = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit9.setEnabled(False)
        self.lineEdit9.setGeometry(QtCore.QRect(10, 20, 691, 20))
        self.lineEdit9.setObjectName("lineEdit9")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton11.setGeometry(QtCore.QRect(810, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.pushButton11.setFont(font)
        self.pushButton11.setDefault(False)
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton23 = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton23.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton23.setFont(font)
        self.pushButton23.setAutoDefault(False)
        self.pushButton23.setDefault(False)
        self.pushButton23.setFlat(False)
        self.pushButton23.setObjectName("pushButton23")
        self.groupBox_60 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_60.setGeometry(QtCore.QRect(810, 20, 91, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_60.setFont(font)
        self.groupBox_60.setObjectName("groupBox_60")
        self.checkBox4 = QtWidgets.QCheckBox(self.groupBox_60)
        self.checkBox4.setGeometry(QtCore.QRect(10, 20, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox4.setPalette(palette)
        self.checkBox4.setObjectName("checkBox4")
        self.checkBox5 = QtWidgets.QCheckBox(self.groupBox_60)
        self.checkBox5.setGeometry(QtCore.QRect(10, 40, 81, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox5.setPalette(palette)
        self.checkBox5.setChecked(False)
        self.checkBox5.setObjectName("checkBox5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 211, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3.setGeometry(QtCore.QRect(110, 20, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.pushButton3.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton3.setFont(font)
        self.pushButton3.setDefault(True)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2.setEnabled(True)
        self.pushButton2.setGeometry(QtCore.QRect(10, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButton2.setFont(font)
        self.pushButton2.setDefault(True)
        self.pushButton2.setObjectName("pushButton2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 80, 931, 291))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_4.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_43 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_43.setGeometry(QtCore.QRect(10, 20, 111, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_43.setFont(font)
        self.groupBox_43.setObjectName("groupBox_43")
        self.comboBox2 = QtWidgets.QComboBox(self.groupBox_43)
        self.comboBox2.setGeometry(QtCore.QRect(10, 20, 91, 22))
        self.comboBox2.setObjectName("comboBox2")
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_41.setGeometry(QtCore.QRect(130, 20, 111, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_41.setFont(font)
        self.groupBox_41.setObjectName("groupBox_41")
        self.comboBox3 = QtWidgets.QComboBox(self.groupBox_41)
        self.comboBox3.setGeometry(QtCore.QRect(10, 20, 91, 22))
        self.comboBox3.setObjectName("comboBox3")
        self.groupBox_45 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_45.setGeometry(QtCore.QRect(250, 20, 111, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_45.setFont(font)
        self.groupBox_45.setObjectName("groupBox_45")
        self.lineEdit1 = QtWidgets.QLineEdit(self.groupBox_45)
        self.lineEdit1.setEnabled(True)
        self.lineEdit1.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_42.setGeometry(QtCore.QRect(370, 20, 111, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_42.setFont(font)
        self.groupBox_42.setObjectName("groupBox_42")
        self.lineEdit2 = QtWidgets.QLineEdit(self.groupBox_42)
        self.lineEdit2.setEnabled(True)
        self.lineEdit2.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit2.setObjectName("lineEdit2")
        self.groupBox_47 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_47.setGeometry(QtCore.QRect(10, 220, 811, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_47.setFont(font)
        self.groupBox_47.setObjectName("groupBox_47")
        self.lineEdit6 = QtWidgets.QLineEdit(self.groupBox_47)
        self.lineEdit6.setEnabled(False)
        self.lineEdit6.setGeometry(QtCore.QRect(10, 20, 491, 20))
        self.lineEdit6.setObjectName("lineEdit6")
        self.pushButton7 = QtWidgets.QPushButton(self.groupBox_47)
        self.pushButton7.setGeometry(QtCore.QRect(610, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton7.setFont(font)
        self.pushButton7.setDefault(True)
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton8 = QtWidgets.QPushButton(self.groupBox_47)
        self.pushButton8.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton8.setFont(font)
        self.pushButton8.setDefault(True)
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton20 = QtWidgets.QPushButton(self.groupBox_47)
        self.pushButton20.setGeometry(QtCore.QRect(510, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton20.setFont(font)
        self.pushButton20.setAutoDefault(False)
        self.pushButton20.setDefault(False)
        self.pushButton20.setFlat(False)
        self.pushButton20.setObjectName("pushButton20")
        self.pushButton13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton13.setGeometry(QtCore.QRect(830, 20, 93, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton13.setFont(font)
        self.pushButton13.setObjectName("pushButton13")
        self.groupBox_44 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_44.setGeometry(QtCore.QRect(610, 20, 101, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_44.setFont(font)
        self.groupBox_44.setObjectName("groupBox_44")
        self.comboBox5 = QtWidgets.QComboBox(self.groupBox_44)
        self.comboBox5.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.comboBox5.setObjectName("comboBox5")
        self.groupBox_46 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_46.setGeometry(QtCore.QRect(720, 20, 101, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_46.setFont(font)
        self.groupBox_46.setObjectName("groupBox_46")
        self.comboBox6 = QtWidgets.QComboBox(self.groupBox_46)
        self.comboBox6.setGeometry(QtCore.QRect(10, 20, 81, 22))
        self.comboBox6.setObjectName("comboBox6")
        self.groupBox_56 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_56.setGeometry(QtCore.QRect(10, 80, 811, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_56.setFont(font)
        self.groupBox_56.setObjectName("groupBox_56")
        self.lineEdit12 = QtWidgets.QLineEdit(self.groupBox_56)
        self.lineEdit12.setEnabled(False)
        self.lineEdit12.setGeometry(QtCore.QRect(10, 20, 791, 20))
        self.lineEdit12.setObjectName("lineEdit12")
        self.groupBox_57 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_57.setGeometry(QtCore.QRect(490, 20, 111, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_57.setFont(font)
        self.groupBox_57.setObjectName("groupBox_57")
        self.lineEdit13 = QtWidgets.QLineEdit(self.groupBox_57)
        self.lineEdit13.setEnabled(True)
        self.lineEdit13.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.lineEdit13.setObjectName("lineEdit13")
        self.groupBox_58 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_58.setGeometry(QtCore.QRect(830, 150, 91, 131))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_58.setFont(font)
        self.groupBox_58.setObjectName("groupBox_58")
        self.checkBox1 = QtWidgets.QCheckBox(self.groupBox_58)
        self.checkBox1.setGeometry(QtCore.QRect(10, 20, 61, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox1.setPalette(palette)
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.groupBox_58)
        self.checkBox2.setGeometry(QtCore.QRect(10, 40, 51, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox2.setPalette(palette)
        self.checkBox2.setChecked(True)
        self.checkBox2.setObjectName("checkBox2")
        self.checkBox3 = QtWidgets.QCheckBox(self.groupBox_58)
        self.checkBox3.setGeometry(QtCore.QRect(10, 60, 51, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox3.setPalette(palette)
        self.checkBox3.setChecked(False)
        self.checkBox3.setObjectName("checkBox3")
        self.checkBox7 = QtWidgets.QCheckBox(self.groupBox_58)
        self.checkBox7.setGeometry(QtCore.QRect(10, 100, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox7.setPalette(palette)
        self.checkBox7.setChecked(True)
        self.checkBox7.setObjectName("checkBox7")
        self.checkBox6 = QtWidgets.QCheckBox(self.groupBox_58)
        self.checkBox6.setGeometry(QtCore.QRect(10, 80, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox6.setPalette(palette)
        self.checkBox6.setChecked(True)
        self.checkBox6.setObjectName("checkBox6")
        self.groupBox_1 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 150, 811, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_1.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.lineEdit5 = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit5.setEnabled(False)
        self.lineEdit5.setGeometry(QtCore.QRect(10, 20, 591, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.pushButton6 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton6.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton6.setFont(font)
        self.pushButton6.setAutoDefault(False)
        self.pushButton6.setDefault(False)
        self.pushButton6.setFlat(False)
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton19 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton19.setGeometry(QtCore.QRect(610, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton19.setFont(font)
        self.pushButton19.setAutoDefault(False)
        self.pushButton19.setDefault(False)
        self.pushButton19.setFlat(False)
        self.pushButton19.setObjectName("pushButton19")
        self.groupBox_59 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_59.setGeometry(QtCore.QRect(830, 80, 91, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_59.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_59.setFont(font)
        self.groupBox_59.setObjectName("groupBox_59")
        self.comboBox9 = QtWidgets.QComboBox(self.groupBox_59)
        self.comboBox9.setGeometry(QtCore.QRect(10, 20, 71, 22))
        self.comboBox9.setObjectName("comboBox9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MIIL LEARNING", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "EXCUTE", None, -1))
        self.pushButton1.setText(QtWidgets.QApplication.translate("MainWindow", "START", None, -1))
        self.groupBox_55.setTitle(QtWidgets.QApplication.translate("MainWindow", "WEIGHT FILE", None, -1))
        self.pushButton9.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton17.setText(QtWidgets.QApplication.translate("MainWindow", "MAP", None, -1))
        self.pushButton24.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_53.setTitle(QtWidgets.QApplication.translate("MainWindow", "EXE FILE", None, -1))
        self.pushButton4.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton25.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_51.setTitle(QtWidgets.QApplication.translate("MainWindow", "MODE", None, -1))
        self.radioButton1.setText(QtWidgets.QApplication.translate("MainWindow", "USE WEIGHT", None, -1))
        self.radioButton2.setText(QtWidgets.QApplication.translate("MainWindow", "START", None, -1))
        self.radioButton3.setText(QtWidgets.QApplication.translate("MainWindow", "PARTIAL", None, -1))
        self.radioButton4.setText(QtWidgets.QApplication.translate("MainWindow", "ANCHORS", None, -1))
        self.radioButton5.setText(QtWidgets.QApplication.translate("MainWindow", "TEST", None, -1))
        self.groupBox_54.setTitle(QtWidgets.QApplication.translate("MainWindow", "# OF GPU", None, -1))
        self.groupBox_52.setTitle(QtWidgets.QApplication.translate("MainWindow", "CONV", None, -1))
        self.lineEdit10.setText(QtWidgets.QApplication.translate("MainWindow", "81", None, -1))
        self.groupBox_48.setTitle(QtWidgets.QApplication.translate("MainWindow", "WIDTH", None, -1))
        self.groupBox_49.setTitle(QtWidgets.QApplication.translate("MainWindow", "HEIGHT", None, -1))
        self.groupBox_50.setTitle(QtWidgets.QApplication.translate("MainWindow", "CLUSTERS", None, -1))
        self.lineEdit11.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.groupBox_23.setTitle(QtWidgets.QApplication.translate("MainWindow", "PARAMETER FILE", None, -1))
        self.pushButton11.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton23.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_60.setTitle(QtWidgets.QApplication.translate("MainWindow", "OPTION", None, -1))
        self.checkBox4.setText(QtWidgets.QApplication.translate("MainWindow", "MAP", None, -1))
        self.checkBox5.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW_IMG", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "STATE", None, -1))
        self.pushButton3.setText(QtWidgets.QApplication.translate("MainWindow", "SAVE SATE", None, -1))
        self.pushButton2.setText(QtWidgets.QApplication.translate("MainWindow", "LOAD STATE", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "CREATE MODEL FILE", None, -1))
        self.groupBox_43.setTitle(QtWidgets.QApplication.translate("MainWindow", "BATCH SIZE", None, -1))
        self.groupBox_41.setTitle(QtWidgets.QApplication.translate("MainWindow", "SUBDIVISIONS", None, -1))
        self.groupBox_45.setTitle(QtWidgets.QApplication.translate("MainWindow", "LEARNING RATE", None, -1))
        self.lineEdit1.setText(QtWidgets.QApplication.translate("MainWindow", "0.0001", None, -1))
        self.groupBox_42.setTitle(QtWidgets.QApplication.translate("MainWindow", "MAX BATCHES", None, -1))
        self.lineEdit2.setText(QtWidgets.QApplication.translate("MainWindow", "10000", None, -1))
        self.groupBox_47.setTitle(QtWidgets.QApplication.translate("MainWindow", "MODEL FILE", None, -1))
        self.pushButton7.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton8.setText(QtWidgets.QApplication.translate("MainWindow", "SAVE", None, -1))
        self.pushButton20.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.pushButton13.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW CFG", None, -1))
        self.groupBox_44.setTitle(QtWidgets.QApplication.translate("MainWindow", "WIDTH", None, -1))
        self.groupBox_46.setTitle(QtWidgets.QApplication.translate("MainWindow", "HEIGHT", None, -1))
        self.groupBox_56.setTitle(QtWidgets.QApplication.translate("MainWindow", "ANCHORS", None, -1))
        self.lineEdit12.setText(QtWidgets.QApplication.translate("MainWindow", "anchors = 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326", None, -1))
        self.groupBox_57.setTitle(QtWidgets.QApplication.translate("MainWindow", "BURN IN", None, -1))
        self.lineEdit13.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.groupBox_58.setTitle(QtWidgets.QApplication.translate("MainWindow", "OPTION", None, -1))
        self.checkBox1.setText(QtWidgets.QApplication.translate("MainWindow", "SMALL", None, -1))
        self.checkBox2.setText(QtWidgets.QApplication.translate("MainWindow", "FLIP", None, -1))
        self.checkBox3.setText(QtWidgets.QApplication.translate("MainWindow", "CONV", None, -1))
        self.checkBox7.setText(QtWidgets.QApplication.translate("MainWindow", "RANDOM", None, -1))
        self.checkBox6.setText(QtWidgets.QApplication.translate("MainWindow", "JITTER", None, -1))
        self.groupBox_1.setTitle(QtWidgets.QApplication.translate("MainWindow", "LABEL FILE", None, -1))
        self.pushButton6.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton19.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_59.setTitle(QtWidgets.QApplication.translate("MainWindow", "MODEL", None, -1))

